# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181024_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
