# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20181025_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='shop/'),
        ),
    ]
