# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20181025_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.ManyToManyField(to='shop.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
